# Generated by Django 3.1.4 on 2020-12-08 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masteruser',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos/'),
        ),
    ]
