# Generated by Django 3.1.4 on 2020-12-15 09:11

from django.conf import settings
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_masteruser_is_master'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defendant_email', models.EmailField(max_length=254)),
                ('text', models.TextField(max_length=500)),
                ('photos', django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(upload_to='complaint_photos/'), blank=True, null=True, size=5)),
                ('documents', django.contrib.postgres.fields.ArrayField(base_field=models.FileField(upload_to='complaint_documents/'), blank=True, null=True, size=5)),
                ('status', models.CharField(choices=[('in process', 'In process'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='in process', max_length=20)),
                ('complaint_creater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=150)),
                ('placement', models.CharField(choices=[('in place', 'In place'), ('not in place', 'Not in place')], default='in place', max_length=20)),
                ('name', models.CharField(choices=[('fix computer', 'Fix computer'), ('fix faucet', 'Fix faucet'), ('clean house', 'Clean house'), ('install windows', 'Install windows'), ('clean sofa', 'Clean sofa')], max_length=50)),
                ('nim_cost_with_materials', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(10000)])),
                ('nim_cost_without_materials', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(10000)])),
            ],
        ),
        migrations.AddField(
            model_name='portfolio',
            name='master',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to='apps.masteruser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='photos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(upload_to='portfolio_photos/'), blank=True, null=True, size=5),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='price',
            field=models.FloatField(default=10, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(10000)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='spending_hours',
            field=models.FloatField(default=2, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(1000)]),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_email', models.EmailField(max_length=254, null=True)),
                ('customer_phone', phonenumber_field.modelfields.PhoneNumberField(help_text='Contact phone number', max_length=128, null=True, region='BY')),
                ('date_of_creating_request', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('in process', 'In process'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='in process', max_length=20)),
                ('customer_text_comment', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('photos', django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(upload_to='order_photos/'), blank=True, null=True, size=5)),
                ('date_time_of_work_begin', models.DateTimeField()),
                ('address', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('work', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_requests', to='apps.work')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=500, null=True)),
                ('rating', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('date', models.DateField(auto_now=True)),
                ('photos', django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(upload_to='review_photos/'), blank=True, null=True, size=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='apps.work')),
            ],
        ),
        migrations.CreateModel(
            name='OrderAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_answer', to='apps.workorder')),
            ],
        ),
        migrations.CreateModel(
            name='ComplaintAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500)),
                ('answered_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints_answer', to=settings.AUTH_USER_MODEL)),
                ('comlaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints_answer', to='apps.complaint')),
            ],
        ),
        migrations.AddField(
            model_name='portfolio',
            name='work',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to='apps.work'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='workorder',
            constraint=models.CheckConstraint(check=models.Q(('customer_email__isnull', False), ('customer_phone__isnull', False), _connector='OR'), name='not_both_phone_email_null'),
        ),
    ]
