# Generated by Django 3.1.4 on 2020-12-15 09:13

from django.db import migrations
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_auto_20201215_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='blacklist',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Contact phone number', max_length=128, null=True, region='BY'),
        ),
        migrations.AddConstraint(
            model_name='blacklist',
            constraint=models.CheckConstraint(
                check=models.Q(('email__isnull', False), ('phone__isnull', False), _connector='OR'),
                name='not_both_phone_email_null_bl_list'),
        ),
    ]
