# Generated by Django 3.1.4 on 2020-12-16 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_blacklist_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='need_materials',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('both', 'Both')], default='no', max_length=5),
        ),
        migrations.AddField(
            model_name='work',
            name='worker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='works', to='apps.masteruser'),
            preserve_default=False,
        ),
    ]
