# Generated by Django 3.1.4 on 2020-12-16 10:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_auto_20201216_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='nim_cost_with_materials',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(10000)]),
        ),
        migrations.AlterField(
            model_name='work',
            name='nim_cost_without_materials',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(10000)]),
        ),
    ]
