# Generated by Django 3.1.4 on 2021-01-04 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_workorder_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Portfolio',
        ),
    ]
