# Generated by Django 3.1.4 on 2021-01-04 10:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_delete_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='rating',
            field=models.FloatField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
