# Generated by Django 3.1.4 on 2021-01-05 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0011_work_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='defendant_address',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='defendant_phone',
            field=models.EmailField(default=375297602582, max_length=254),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='complaint',
            constraint=models.CheckConstraint(check=models.Q(('defendant_email__isnull', False), ('defendant_phone__isnull', False), _connector='OR'), name='not_both_phone_email_null_complaint'),
        ),
    ]
