# Generated by Django 3.1.4 on 2021-01-05 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0014_complaint_date_of_creating_complaint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaintanswer',
            old_name='comlaint',
            new_name='complaint',
        ),
    ]
