# Generated by Django 3.1.4 on 2021-01-06 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0015_auto_20210105_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masteruser',
            name='rating',
        ),
    ]
